on: [push, workflow_dispatch]
jobs:
    build-and-test:
        runs-on: self-hosted
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21.x'
            - name: Install Dependencies
              run: go get .
            - name: Build
              run: go build -v .
            - name: Test
              run: go test
            